// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pilmvwzurnabqbqayovl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpbG12d3p1cm5hYnFicWF5b3ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzY4OTQsImV4cCI6MjA2MTM1Mjg5NH0.zIWrmIoBufjJ329SAZm5qnmofTuNlgIrOvTto60Ozcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);